{
    'name': 'Theme Eventzo',
    'summary': 'A Full Packaged Event Managment System',
    'category': 'Theme',
    'version': '19.0.1.0',
    'author': 'TECHVEX',
    'depends': [
        'website',
        'theme_default',
    ],
    'data': [

        "views/theme_eventzo_inherited.xml",
        "views/homepage/hero.xml",
        "views/homepage/status.xml",
        "views/homepage/iso.xml",
        "views/homepage/cta.xml",
        "views/homepage/service.xml",
        "views/homepage/venue_banner.xml",
        "views/homepage/contact.xml",
        "views/homepage/about_hero.xml",
        "views/homepage/about_content.xml",
        "views/homepage/hero_gallery.xml",
        "views/homepage/gallery_content.xml",
        "views/homepage/contact_page.xml",
        "views/homepage/contact_form.xml",
        "views/homepage/car_service.xml",
        "views/homepage/car_enq.xml",
        "views/homepage/wedding.xml",
        "views/homepage/wedding_content.xml",
        "views/homepage/wedding_service_details.xml",
        "views/homepage/corporate_hero.xml",
        "views/homepage/corporate_detailed.xml",
        "views/homepage/party.xml",
        "views/homepage/party_content.xml",
        "views/homepage/party_service.xml",
        "views/homepage/photograpghy.xml",
        "views/homepage/photogrpghy_content.xml",
        "views/homepage/wedding_grid.xml",
        "views/homepage/photogrphy_book.xml",
        "views/header.xml",
        "views/footer.xml"

    ],
    'assets': {
        'web.assets_frontend': [
            'theme_eventzo/static/src/scss/hero.scss',
            'theme_eventzo/static/src/scss/status.scss',
            'theme_eventzo/static/src/scss/header.scss',
            'theme_eventzo/static/src/scss/iso.scss',
            'theme_eventzo/static/src/scss/cta.scss',
            'theme_eventzo/static/src/scss/service.scss',
            'theme_eventzo/static/src/scss/venue_banner.scss',
            'theme_eventzo/static/src/scss/contact.scss',
            'theme_eventzo/static/src/scss/about_hero.scss',
            'theme_eventzo/static/src/scss/footer.scss',
            'theme_eventzo/static/src/scss/about_content.scss',
            'theme_eventzo/static/src/scss/hero_gallery.scss',
            'theme_eventzo/static/src/scss/gallery_content.scss',
            'theme_eventzo/static/src/scss/contact_page.scss',
            'theme_eventzo/static/src/scss/contact_form.scss',
            'theme_eventzo/static/src/scss/car_service.scss',
            'theme_eventzo/static/src/scss/car_enq.scss',
            'theme_eventzo/static/src/scss/wedding.scss',
            'theme_eventzo/static/src/scss/wedding_content.scss',
            'theme_eventzo/static/src/scss/wedding_service_details.scss',
            'theme_eventzo/static/src/scss/corporate_hero.scss',
            'theme_eventzo/static/src/scss/corporate_detailed.scss',
            'theme_eventzo/static/src/scss/party.scss',
            'theme_eventzo/static/src/scss/party_content.scss',
            'theme_eventzo/static/src/scss/party_service.scss',
            'theme_eventzo/static/src/scss/photograpghy.scss',
            'theme_eventzo/static/src/scss/photogrphy.scss',
            'theme_eventzo/static/src/scss/wedding_grid.scss',
            'theme_eventzo/static/src/scss/photogrpghy_book.scss',




            'theme_eventzo/static/src/js/animations.js',
            'theme_eventzo/static/src/js/status.js',
            'theme_eventzo/static/src/js/header.js',
            'theme_eventzo/static/src/js/cta.js',
            'theme_eventzo/static/src/js/service.js',
            'theme_eventzo/static/src/js/venue_banner.js',
            'theme_eventzo/static/src/js/gallery_content.js',
            'theme_eventzo/static/src/js/contact_page.js',
            'theme_eventzo/static/src/js/contact_form.js',
            'theme_eventzo/static/src/js/car_enq.js',
            'theme_eventzo/static/src/js/wedding_grid.js',


        ],
    },


    'images': [
        'static/description/eventzo_cover.gif',
        'static/description/eventzo_screenshot.gif',

    ],

    'support': 'techvex.dev@gmail.com',
    'price': 13.00,
    'live_test_url': 'http://13.48.248.147:8070',
    'currency': 'USD',
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'OPL-1',
}
